# -*- coding: utf-8 -*-
"""F4F_DataAnalysisQ2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlI0Mx1iT90PJIbD6nYT0BrJi7wrOUQH
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/q2_data.xlsx - Data_.csv')

df.head(2)
print(df.columns)

df.isnull().sum()

len(df)

channel = df['Reference/From where did they come to know about us?'].value_counts()
channel_data = pd.DataFrame(channel).reset_index()

dates = df['Date'].value_counts()
frequency = pd.DataFrame(dates).reset_index()
frequency.head()

ref_col = df['Reference/From where did they come to know about us?'].unique()

filtered_df = [df[df['Reference/From where did they come to know about us?']==ref_col[x]] for x in range(len(ref_col))]

ds = pd.concat(filtered_df,ignore_index=True)

ds.head()

from collections import Counter
comment_count = Counter(df['comments'])
df_comment = pd.DataFrame(comment_count.items(),columns=['Comment','Count']).sort_values(by='Count',ascending=False)
df_comment.head()